import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import * as api from './researchApi'
import { ResearchView } from './ResearchView'

vi.mock('./researchApi', () => ({ listResearch: vi.fn(), getResearch: vi.fn(), createResearch: vi.fn(), appendResearchEntry: vi.fn(), updateResearchStatus: vi.fn() }))
const topic = (id: string): api.ResearchTopic => ({ id, title: `主题${id}`, question: '', description: null, status: 'collecting', conclusion: '原结论', limitations: null, created_at: '2026-10-03T00:00:00Z', updated_at: '2026-10-03T00:00:00Z', entries: [], conclusion_history: [] })
const a = topic('A'); const b = topic('B')
// 通过实际可见的下拉入口选择，避免隐藏原生代理掩盖交互问题。
const chooseStatus = (label: string, option: string) => {
  fireEvent.click(screen.getByRole('combobox', { name: new RegExp(`^${label}：`) }))
  fireEvent.click(screen.getByRole('option', { name: option }))
}
const openA = async () => { render(<ResearchView />); fireEvent.click(await screen.findByRole('button', { name: /主题A/ })); await waitFor(() => expect(api.getResearch).toHaveBeenCalledWith('A')) }
describe('调研笔记', () => {
  afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals() })
  beforeEach(() => {
    sessionStorage.clear(); vi.clearAllMocks()
    vi.mocked(api.listResearch).mockResolvedValue({ items: [a, b], summary: { total: 2, collecting: 2, comparing: 0, archived: 0 } })
    vi.mocked(api.getResearch).mockImplementation(async id => topic(id))
  })
  it.each([false, true])('打开详情阻止默认获焦滚动，只有窄屏显式定位顶部：%s', async compact => {
    vi.stubGlobal('matchMedia', vi.fn(() => ({ matches: compact })))
    render(<ResearchView />)
    const button = await screen.findByRole('button', { name: /主题A/ })
    const pane = screen.getByLabelText('调研详情')
    const focus = vi.spyOn(pane, 'focus')
    const scroll = vi.fn()
    pane.scrollIntoView = scroll
    fireEvent.click(button)
    expect(focus).toHaveBeenCalledWith({ preventScroll: true })
    if (compact) expect(scroll).toHaveBeenCalledWith({ block: 'start' })
    else expect(scroll).not.toHaveBeenCalled()
    await waitFor(() => expect(api.getResearch).toHaveBeenCalledWith('A'))
    // 详情刷新不能重复定位并覆盖用户已移动的阅读位置。
    expect(focus).toHaveBeenCalledTimes(1)
  })
  it('只需一句话创建，失败保留输入', async () => {
    vi.mocked(api.createResearch).mockRejectedValue(new Error('保存失败'))
    render(<ResearchView />); await screen.findByRole('button', { name: /主题A/ })
    fireEvent.change(screen.getByLabelText('随手记一个问题'), { target: { value: '要不要回水管' } })
    fireEvent.click(screen.getByRole('button', { name: '记下问题' }))
    await screen.findByText('保存失败')
    expect((screen.getByLabelText('随手记一个问题') as HTMLInputElement).value).toBe('要不要回水管')
    expect(api.createResearch).toHaveBeenCalledWith('要不要回水管')
  })
  it('保留不同主题的调研草稿', async () => {
    await openA()
    fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: 'A的研究' } })
    fireEvent.click(screen.getByRole('button', { name: /主题B/ }))
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('')
    fireEvent.click(screen.getByRole('button', { name: /主题A/ }))
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('A的研究')
  })
  it('A保存晚返回不会切走B，B草稿保留', async () => {
    let resolve!: (value: api.ResearchTopic) => void
    vi.mocked(api.appendResearchEntry).mockImplementation(() => new Promise(done => { resolve = done }))
    await openA(); fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: 'A研究' } })
    fireEvent.click(screen.getByRole('button', { name: '追加调研' }))
    expect(screen.getByLabelText('本次调研').closest('fieldset')?.disabled).toBe(true)
    fireEvent.click(screen.getByRole('button', { name: /主题B/ }))
    fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: 'B未保存' } })
    await act(async () => resolve(a))
    expect(screen.getByRole('heading', { name: '主题B' })).toBeTruthy()
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('B未保存')
  })
  it('过期详情请求失败不显示在新主题下', async () => {
    let reject!: (reason: Error) => void
    vi.mocked(api.getResearch).mockImplementation(id => id === 'A' ? new Promise((_, fail) => { reject = fail }) : Promise.resolve(b))
    await openA(); fireEvent.click(screen.getByRole('button', { name: /主题B/ }))
    await act(async () => reject(new Error('A加载失败')))
    expect(screen.queryByText('A加载失败')).toBeNull()
  })
  it('A保存中切走再返回仍禁止重复写入，完成后同步草稿与反馈', async () => {
    let resolve!: (value: api.ResearchTopic) => void
    vi.mocked(api.appendResearchEntry).mockImplementation(() => new Promise(done => { resolve = done }))
    await openA()
    fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: 'A研究' } })
    fireEvent.click(screen.getByRole('button', { name: '追加调研' }))
    fireEvent.click(screen.getByRole('button', { name: /主题B/ }))
    expect(screen.getByLabelText('本次调研').closest('fieldset')?.disabled).toBe(false)
    fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: 'B草稿' } })
    fireEvent.click(screen.getByRole('button', { name: /主题A/ }))
    expect(screen.getByLabelText('本次调研').closest('fieldset')?.disabled).toBe(true)
    expect(screen.getByRole('button', { name: '保存调研中…' }).hasAttribute('disabled')).toBe(true)
    await act(async () => resolve(a))
    expect(screen.getByLabelText('本次调研').closest('fieldset')?.disabled).toBe(false)
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('')
    expect(screen.getByText('本次调研已保存。')).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: /主题B/ }))
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('B草稿')
  })
  it('同主题详情旧请求不能覆盖刚保存的调研', async () => {
    let resolve!: (value: api.ResearchTopic) => void
    vi.mocked(api.getResearch).mockImplementation(() => new Promise(done => { resolve = done }))
    const saved = { ...a, entries: [{ id: 'new', record_id: 'A', research_date: '2026-10-07', content: '最新调研', sources: [], uncertainties: null, created_at: a.created_at }] }
    vi.mocked(api.appendResearchEntry).mockResolvedValue(saved)
    await openA()
    fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: '最新调研' } })
    fireEvent.click(screen.getByRole('button', { name: '追加调研' }))
    await screen.findByText('最新调研', { selector: 'p' })
    await act(async () => resolve(a))
    expect(screen.getByText('最新调研', { selector: 'p' })).toBeTruthy()
  })
  it('搜索研究内容并按状态筛选，保留当前详情', async () => {
    vi.mocked(api.listResearch).mockResolvedValue({ items: [{ ...a, status: 'archived' }, b], summary: { total: 2, collecting: 1, comparing: 0, archived: 1 } })
    await openA()
    chooseStatus('筛选状态', '已归档')
    expect(screen.queryByRole('button', { name: /主题B/ })).toBeNull()
    fireEvent.change(screen.getByLabelText('搜索调研'), { target: { value: '不存在的主题' } })
    expect(screen.getByText('当前筛选下没有调研主题。')).toBeTruthy()
    expect(screen.getByRole('heading', { name: '主题A' })).toBeTruthy()
  })
  it('旧已结论主题显示为调研中，结论不参与搜索且仅提供三种状态', async () => {
    const legacy = { ...a, status: 'concluded' as const }
    vi.mocked(api.listResearch).mockResolvedValue({ items: [legacy, b], summary: { total: 2, collecting: 1, comparing: 1, archived: 0 } })
    vi.mocked(api.getResearch).mockResolvedValue(legacy)
    await openA()
    const state = screen.getByRole('combobox', { name: '主题状态：调研中' })
    expect(state.closest('label')?.className).toBe('research-status-row')
    fireEvent.click(state)
    expect(state.getAttribute('aria-expanded')).toBe('true')
    expect(screen.getAllByRole('option').map(option => option.textContent)).toEqual(['待调研', '调研中', '已归档'])
    fireEvent.keyDown(state, { key: 'Escape' })
    expect(state.getAttribute('aria-expanded')).toBe('false')
    // 两个入口均使用公共组件；原生 select 只保留隐藏表单代理。
    expect(screen.getAllByRole('combobox')).toHaveLength(2)
    expect([...document.querySelectorAll('select')].every(select => select.getAttribute('aria-hidden') === 'true')).toBe(true)
    chooseStatus('筛选状态', '调研中')
    expect(screen.getByRole('button', { name: /主题A/ })).toBeTruthy()
    expect(screen.queryByRole('button', { name: /主题B/ })).toBeNull()
    fireEvent.change(screen.getByLabelText('搜索调研'), { target: { value: '原结论' } })
    expect(screen.queryByRole('button', { name: /主题A/ })).toBeNull()
    expect(screen.getByText('当前筛选下没有调研主题。')).toBeTruthy()
  })
  it('归档后可恢复原状态，来源只开放HTTP链接', async () => {
    const archived = { ...a, status: 'archived' as const, entries: [{ id: 'e1', record_id: 'A', research_date: '2026-10-03', content: '资料', sources: ['https://example.com', 'javascript:alert(1)', '书籍'], uncertainties: null, created_at: a.created_at }] }
    vi.mocked(api.getResearch).mockResolvedValue(archived)
    vi.mocked(api.updateResearchStatus).mockResolvedValue(a)
    await openA(); await screen.findByRole('link', { name: 'https://example.com' })
    expect(screen.queryByRole('link', { name: 'javascript:alert(1)' })).toBeNull()
    chooseStatus('主题状态', '待调研')
    await waitFor(() => expect(api.updateResearchStatus).toHaveBeenCalledWith('A', 'collecting'))
  })
  it('进入详情和返回恢复焦点，筛选与未保存草稿保留', async () => {
    await openA()
    expect(document.activeElement?.getAttribute('aria-label')).toBe('调研详情：主题A')
    fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: '未完成的比较' } })
    fireEvent.change(screen.getByLabelText('搜索调研'), { target: { value: '主题A' } })
    fireEvent.click(screen.getByRole('button', { name: '返回主题列表' }))
    expect(document.activeElement).toBe(screen.getByRole('button', { name: /主题A/ }))
    expect((screen.getByLabelText('搜索调研') as HTMLInputElement).value).toBe('主题A')
    fireEvent.click(screen.getByRole('button', { name: /主题A/ }))
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('未完成的比较')
    fireEvent.change(screen.getByLabelText('搜索调研'), { target: { value: '没有匹配' } })
    fireEvent.click(screen.getByRole('button', { name: '清除筛选' }))
    expect(screen.getByRole('button', { name: /主题B/ })).toBeTruthy()
  })
  it('近期调研优先展示，旧结论及历史不展示', async () => {
    const entries = Array.from({ length: 5 }, (_, i) => ({ id: `e${i}`, record_id: 'A', research_date: `2026-10-0${i + 1}`, content: `资料${i}`, sources: [], uncertainties: null, created_at: a.created_at }))
    vi.mocked(api.getResearch).mockResolvedValue({ ...a, entries, conclusion_history: [{ id: 'h1', record_id: 'A', conclusion: '旧判断', reason: '原始依据', entry_id: 'e0', created_at: a.created_at }] })
    await openA(); await screen.findByText('资料4')
    expect(screen.queryByText('资料0')).toBeNull()
    const editor = screen.getByLabelText('本次调研').closest('section')!
    expect(editor.compareDocumentPosition(screen.getByText('资料4')) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: '查看全部 5 次调研' }))
    expect(screen.getByText('资料0')).toBeTruthy()
    expect(screen.queryByText('旧判断')).toBeNull()
    expect(screen.queryByText('原结论')).toBeNull()
    expect(screen.queryByLabelText('新结论')).toBeNull()
  })
  it('追加失败反馈就近且保留输入，重试成功显示保存结果', async () => {
    vi.mocked(api.appendResearchEntry).mockRejectedValueOnce(new Error('网络中断，请重试')).mockResolvedValue(a)
    await openA()
    fireEvent.change(screen.getByLabelText('本次调研'), { target: { value: '对比材料' } })
    fireEvent.click(screen.getByRole('button', { name: '追加调研' }))
    expect(screen.getByRole('button', { name: '保存调研中…' })).toBeTruthy()
    const failure = await screen.findByRole('alert')
    expect(failure.closest('form')).toBe(screen.getByLabelText('本次调研').closest('form'))
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('对比材料')
    fireEvent.click(screen.getByRole('button', { name: '追加调研' }))
    await screen.findByText('本次调研已保存。')
    expect(screen.queryByText('网络中断，请重试')).toBeNull()
    expect((screen.getByLabelText('本次调研') as HTMLTextAreaElement).value).toBe('')
  })
})
